---
kind: Pod
apiVersion: v1
metadata:
  name: pod-annotation
  annotations:
    builder: "lJE(arjleun@naver.com)"
    buildDate: "2025-10-01"
    imageRegistry: "docker.io/library/nginx:1.14"
spec:
  containers:
    - name: nginx
      image: nginx:1.14
      ports:
        - containerPort: 80