---
# tasks file for ansible_openwrtwireless
- name: MMN openwrtwireless - Make sure wireless deploypath exists
  ansible.builtin.file:
    path: "{{ openwrt_wireless_deploypath }}"
    state: directory
- name: MMN openwrtwireless - Merge devices and interfaces
  import_tasks: 1merge.yml
- name: MMN openwrtwireless - deploy wireless config
  ansible.builtin.template:
    src: "wireless.jinja2"
    dest: "{{ openwrt_wireless_deploypath }}/{{ openwrt_wireless_deployfile }}"
    backup: "{{ openwrt_wireless_backupconfig | default(false)}}"
    mode: "0600"
  when: openwrt_wifi_devices is defined
  notify: restart wireless
