---
kind: Service
apiVersion: v1
metadata:
  name: webapp-nginx-svc
spec:
  type: ClusterIP
  clusterIP: 10.100.10.10
  selector:
    app: webapp
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP 
