---
kind: Pod
apiVersion: v1
metadata:
  name: nginx-pod-resources
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
      - containerPort: 80
    resources:
      limits:
        cpu: 6
        memory: 250Mi
        