#borgmatic_commandname_borgmatic: "borgmatic"
#borgmatic_default_srcdirs:
#  - "/etc"
#  - "/opt"
#  - "/home"
#  - "/root"
borgmatic_fileconfig: "config.yaml"
borgmatic_fileconfig_group: "root"
borgmatic_fileconfig_owner: "root"
#borgmatic_pathconfig: "/etc/borgmatic"
#borgmatic_pathconfig_group: "root"
#borgmatic_pathconfig_owner: "root"
#borgmatic_pathcron: "/etc/cron.d"
#borgmatic_pip_package: "python3-pip"
borgmatic_file_sshknownhosts: "/etc/ssh/ssh_known_hosts"
