---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongodb-express
  labels:
    app: mongodb-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-express
  template:
    metadata:
      name: mongodb-express-pod
      labels:
        app: mongodb-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express:1.0.2-18
          ports:  
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_URL
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: database_url
            - name: ME_CONFIG_BASICAUTH_ENABLED
              value: "true"
            - name: ME_CONFIG_BASICAUTH_USERNAME
              value: "root"
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password

---
kind: Service
apiVersion: v1
metadata:
  name: mongo-express-service
spec:
  type: LoadBalancer
  selector:
    app: mongo-express
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081