---
# defaults file for ansible_restic
restic_cron_name: "resticbackup"
restic_cron_hourrange_start: 1
restic_cron_hourrange_end: 6
restic_prune_hourrange_start: 7
restic_prune_hourrange_end: 9
restic_cron_minuterange_start: 1
restic_cron_minuterange_end: 59
restic_prune_minuterange_start: 1
restic_prune_minuterange_end: 59
restic_cron_hour: "{{ restic_cron_hourrange_end | random(start=restic_cron_hourrange_start, seed=inventory_hostname) }}"
restic_cron_minute: "{{ restic_cron_minuterange_end | random(start=restic_cron_minuterange_start, seed=inventory_hostname) }}"
restic_prune_hour: "{{ restic_prune_hourrange_end | random(start=restic_prune_hourrange_start, seed=inventory_hostname) }}"
restic_prune_minute: "{{ restic_prune_minuterange_end | random(start=restic_prune_minuterange_start, seed=inventory_hostname) }}"
restic_cron_manage: true
restic_ssh_manage: true
restic_keepweekly: 3
restic_keepdaily: 9
restic_keepmonthly: 2
restic_deployroot: "/"
restic_deploypath: "{{ restic_deployroot }}etc"
restic_deployfile: "restic"
restic_deploypath_sysupgrade: "{{ restic_deployroot }}etc"
restic_deployfile_sysupgrade: "sysupgrade.conf"
restic_deploypath_passwordfile: "{{ restic_deployroot }}etc"
restic_deployfile_passwordfile: "resticpassword"
restic_deploypath_knownhosts: "{{ restic_deployroot }}root/.ssh"
restic_deployfile_knownhosts: "known_hosts"
