---
#############################################################
# Play 01: .htaccess 파일 사용하는 웹서버 복원 작업
  # 1. 방화벽 제거 - http
  # 2. 서비스 중지 - httpd
  # 3. 서비스 설정 제거
  #   - /var/www/html/.htaccess
  #   - /var/www/html/index.html
  #   - /etc/httpd/secrets/htpasswd
  # 4. 패키지 제거 - httpd, mode_ssl
##############################################################

- name: Play1. 고급 웹서버 구축 복원 작업
  hosts: ansible1.example.com
  vars_files:
    - vars/file.yml
  tasks:

    - name: 1) 방화벽 제거 - http
      ansible.posix.firewalld:
        service: "{{ fw_80 }}"
        permanent: true
        state: disabled
        immediate: true

    - name: 2) 서비스 중지  - httpd
      ansible.builtin.systemd:
        name: "{{ web_svc }}"
        state: stopped
        enabled: false

    - name: 3) 서비스 설정 삭제
      ansible.builtin.file:
        name: "{{ item }}"
        state: absent
      loop:
        - "{{ web_root }}/index.html"
        - "{{ web_root }}/.htaccess"
        - "{{ secrets_dir }}"

    - name: 4) 패키지 제거
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: absent
      loop:
        - "{{ web_pkg }}"  
        - "{{ ssl_pkg }}"  



