---
galaxy_info:
  role_name: ansible_openwrtquagga
  author: Jochen Demmer
  description: installs and configures quagga for OpenWrt
  company: libcom.de
  issue_tracker_url: https://github.com/imp1sh/ansible_managemynetwork/issues
  license: BSD-3-Clause
  min_ansible_version: "2.9"
  platforms:
    - name: OpenWRT
      versions:
        - "22.03"
  galaxy_tags: [openwrt, lede, quagga, routing]
dependencies:
  - role: imp1sh.ansible_managemynetwork.ansible_packages
    vars:
      packages_installrole:
        - quagga
        - quagga-libzebra
        - quagga-vtysh
        - quagga-watchquagga
        - quagga-zebra
