download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/imp1sh-ansible_managemynetwork-0.8.0.tar.gz
format_version: 1.0.0
name: ansible_managemynetwork
namespace: imp1sh
server: https://galaxy.ansible.com/api/
signatures: []
version: 0.8.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/imp1sh/ansible_managemynetwork/versions/0.8.0/
