---
# vars file for ansible_openwrtimagebuilder
openwrt_imagebuilder_builddir: "/tmp/openwrt_imagebuilder"
openwrt_imagebuilder_outputdir: "/tmp/openwrt_imagebuilder_images"
openwrt_imagebuilder_downloadurl: "https://downloads.openwrt.org/releases/24.10.2/targets/x86/64/openwrt-imagebuilder-24.10.2-x86-64.Linux-x86_64.tar.zst"
openwrt_imagebuilder_filesdir: "files"
