# Merge Interfaces
- name: merge group interfaces
  ansible.builtin.set_fact:
    openwrt_network_interfacesmergedgroup: "{{ openwrt_network_interfacesgroup.keys() | list | intersect(group_names) | map('extract', openwrt_network_interfacesgroup) | combine }}"
  when: openwrt_network_interfacesgroup is defined
- name: combine all interfaces into openwrt_network_interfaces
  ansible.builtin.set_fact:
    openwrt_network_interfaces: "{{ openwrt_network_interfaceshost | default({}) | combine(openwrt_network_interfacesmergedgroup | default({}) ) }}"

# Merge Devices
- name: merge group devices
  ansible.builtin.set_fact:
    openwrt_network_devicesmergedgroup: "{{ openwrt_network_devicesgroup.keys() | list | intersect(group_names) | map('extract', openwrt_network_devicesgroup) | combine }}"
  when: openwrt_network_devicesgroup is defined
- name: combine all devices into openwrt_network_devices
  ansible.builtin.set_fact:
    openwrt_network_devices: "{{ openwrt_network_deviceshost | default({}) | combine(openwrt_network_devicesmergedgroup | default({}) ) }}"

# Merge VLAN Devices
- name: Combine vlan group devices that the host belongs to into one list variable
  ansible.builtin.set_fact:
    openwrt_network_bridge_vlanmergedgroup: "{{ openwrt_network_bridge_vlangroup.keys() | list | intersect(group_names) | map('extract', openwrt_network_bridge_vlangroup) | list | flatten }}"
  when: openwrt_network_bridge_vlangroup is defined
- name: combine all bridge_vlan into openwrt_network_bridge_vlan
  ansible.builtin.set_fact:
    openwrt_network_bridge_vlan: "{{ openwrt_network_bridge_vlanhost | default([]) + openwrt_network_bridge_vlanmergedgroup | default([]) }}"

# Merge Rules4
- name: MMN network - Combine to mergedgroup rules4
  ansible.builtin.set_fact:
    openwrt_network_rules4mergedgroup: "{{ openwrt_network_rules4group.keys() | list | intersect(group_names) | map('extract', openwrt_network_rules4group) | list | flatten }}"
  when: openwrt_network_rules4group is defined
- name: MMN network - Merge rules4 into one
  ansible.builtin.set_fact:
    openwrt_network_rules4: "{{ openwrt_network_rules4host | default({}) | combine(openwrt_network_rules4mergedgroup | default({}) ) }}"
# Merge Rules6
- name: MMN network - Combine to mergedgroup rules6
  ansible.builtin.set_fact:
    openwrt_network_rules6mergedgroup: "{{ openwrt_network_rules6group.keys | list | intersect(group_names) | map('extract', openwrt_network_rules6group) | list | flatten }}"
  when: openwrt_network_rules6group is defined
- name: MMN network - Merge rules6 into one
  ansible.builtin.set_fact:
    openwrt_network_rules6: "{{ openwrt_network_rules6host | default({}) | combine(openwrt_network_rules6mergedgroup | default({}) ) }}"
