---
# 동작되는 파드내의 컨테이너에 /tmp/healthy 파일이 있는지 5초마다 확인한다.
# 파드 실행 후 10초부터 검사한다.
# 성공횟수는 1번, 실패 횟수는 연속 2회로 구성한다.
kind: Pod
apiVersion: v1
metadata:
  name: liveness-pod
spec:
  containers:
  - name: busybox-container
    image: busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 3600
    livenessProbe:
      exec:
        command:
          - ls
          - /tmp/healthy  
      initialDelaySeconds: 10
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 2
      timeoutSeconds: 1