---
# Update talosctl
# not yet working
#- name: MMN Talos - Update talosctl configs (VIP)
#  ansible.builtin.command: talosctl config endpoint {{ talos_cluster.value.controlplane_vip | ansible.utils.ipaddr('address') }} --talosconfig {{ talos_config_file }}
#  changed_when: true
#  when: talos_cluster.value.controlplane_vip is defined

- name: MMN Talos - Update talosctl configs (nonVIP)
  ansible.builtin.command: talosctl config endpoint {{ talos_cluster.value.hosts_controlplane[0].ip4[0] | ansible.utils.ipaddr('address') }} --talosconfig {{ talos_config_file }}
  changed_when: true
    #when: talos_cluster.value.controlplane_vip is not defined

- name: MMN Talos - Update talosctl configs
  ansible.builtin.command: talosctl config node {{ talos_cluster.value.hosts_controlplane[0].ip4[0] | ansible.utils.ipaddr('address') }} --talosconfig {{ talos_config_file }}
  changed_when: true

  #################################
  #           BOOTSTRAP           #
  #################################
- name: MMN Talos - Keep trying to bootstrap
  ansible.builtin.command: "talosctl bootstrap"
  environment:
    TALOSCONFIG: "{{ talosctl_config_path }}" 
  register: talos_bootstrap_result
  retries: 15
  delay: 30
  until: talos_bootstrap_result.rc == 0
  changed_when: talos_bootstrap_result.rc == 0

# Grab kubeconfig
#- name: MMN Talos - Get kubeconfig (VIP)
#  ansible.builtin.command: "talosctl kubeconfig {{ talos_config_path }} -e {{ talos_cluster.value.controlplane_vip }}"
#  environment:
#    TALOSCONFIG: "{{ talosctl_config_path }}" 
#  changed_when: true
#  when: talos_cluster.value.controlplane_vip is defined

- name: MMN Talos - Get kubeconfig (nonVIP)
  # removed explicit talosconfig due to setting env var
  ansible.builtin.command: "talosctl kubeconfig {{ talos_config_path }}"
  environment:
    TALOSCONFIG: "{{ talosctl_config_path }}" 
  changed_when: true
    #when: talos_cluster.value.controlplane_vip is not defined
