---
# tasks file for ansible_openwrtfstab
- name: Make sure deploypath config exists
  ansible.builtin.file:
    path: "{{ openwrt_fstab_deploypath }}"
    state: directory
- name: Install needed packages
  block:
    - name: Set install role vars
      ansible.builtin.set_fact:
        packages_installrole:
          - "block-mount"
          - "kmod-usb-storage"
          - "kmod-nvme"
    - name: Call packages role
      ansible.builtin.include_role:
        name: imp1sh.ansible_managemynetwork.ansible_packages
  when: not openwrt_fstab_runimagebuilder | default(false)
- name: Deploy fstab config
  ansible.builtin.template:
    src: fstab.j2
    dest: "{{ openwrt_fstab_deploypath }}/{{ openwrt_fstab_deployfile }}"
  notify: fstab mount
