---
galaxy_info:
  role_name: ansible_talos
  author: Jochen Demmer
  description: Setup process for talos cluster in maintenance mode. Based upon https://github.com/JamesTurland/JimsGarage/tree/main/Ansible/Playbooks/Talos
  company: libcom.de
  issue_tracker_url: https://github.com/imp1sh/ansible_managemynetwork/issues
  license: BSD-3-Clause
  min_ansible_version: "2.9"
  platforms:
    - name: Alpine
      versions:
      - all
    - name: Debian
      versions:
        - all
    - name: EL
      version:
      - 5
      - 6
      - 7
      - 8
      - 9
    - name: FreeBSD
      versions:
      - all
  galaxy_tags: [talos, kubernetes, k8s, bootstrap, cluster]
dependencies: []
