---
kind: Job
apiVersion: batch/v1
metadata:
  name: os-job
spec:
  template:
    spec:
      containers:
        - name: os-container
          image: centos:7
          command: ["sh", "-c", "echo Hello OS; sleep 30; echo Bye OS"] 
      restartPolicy: Never