- name: MMN Restic - Assemble repository string
  include_tasks: xassemblerepo.yml
- name: MMN Restic - Init repository
  ansible.builtin.shell: "source {{ restic_deploypath }}/{{ restic_deployfile }}_{{ backupitem['name'] }} && restic init -p {{ restic_deploypath_passwordfile }}/{{ restic_deployfile_passwordfile }}_{{ backupitem['name'] }} -r {{ assembledrepo }}"
  register: restic_init
  failed_when:
    - restic_init.rc != 0
    - not 'config file already exists' in restic_init.stderr
    - not 'config already initialized' in restic_init.stderr
    - not 'config already exists' in restic_init.stderr
  when: backupitem['state'] == 'present'
