---
- name: Restore playbook.yml
  hosts: all
  vars:
    web_package: httpd
    db_package: mariadb-server
    db_service: mariadb
  tasks:

    - name: 복원 작업
      block:
        - name: "{{ db_service }} 서비스 중지" 
          ansible.builtin.service:
            name: "{{ db_service }}"
            state: stopped

        - name: "{{ web_package }} 패키지 삭제"
          ansible.builtin.yum:
            name: 
              - "{{ web_package }}"
              - "{{ db_package }}"
            state: absent

      rescue:
        - name: 패키지 삭제 에러 메세지
          ansible.builtin.debug:
            msg: "[ FAIL ] {{ web_package }}, {{ db_package }} 패키지 삭제가 되지 않았습니다."
