---
# handlers file for ansible_openwrtnetwork
- name: restart network
  ansible.builtin.service:
    name: network
    state: restarted
  when:
    - not openwrt_network_runimagebuilder | default(false)
    - not openwrt_network_skiprestart | default(false)
- name: restart_keepalived
  ansible.builtin.service:
    name: keepalived
    state: restarted
  when:
    - not openwrt_network_runimagebuilder | default(false)
- name: restart_conntrackd
  ansible.builtin.service:
    name: conntrackd
    state: restarted
  when:
    - not openwrt_network_runimagebuilder | default(false)
