---
kind: Pod
apiVersion: v1
metadata:
  name: web
spec:
  containers:
    - name: nginx
      image: nginx:1.14
      ports:
        - containerPort: 80 
      volumeMounts:
        - name: html
          # mount /webdata /usr/share/nginx/html
          mountPath: /usr/share/nginx/html
  volumes:
    - name: html
      hostPath: 
        path: /webdata