---
- name: MMN users - Checking the following user
  ansible.builtin.debug:
    var: user.key

# Check for group based assignments
- name: MMN users - Check if subelement exists
  ansible.builtin.set_fact:
    system_users_elementcheck_group: "{{ system_users_create_on_hostgroups[user.key] is defined }}"

- name: MMN users - check if host is in group
  ansible.builtin.set_fact:
    list_of_users: "{{ list_of_users + [ user.key ] }}"
  when:
    - system_users_elementcheck_group
    - system_users_create_on_hostgroups[user.key] | intersect(group_names) | length > 0

# Check for individual host assigments
- name: MMN users - Individual host assignment check
  block:
    - name: check if subelement exists in individual list
      ansible.builtin.set_fact:
        system_users_elementcheck_individual: "{{ system_users_create_on_hosts[user.key] is defined }}"

    - name: MMN users - Check if user is in hostlist
      ansible.builtin.set_fact:
        list_of_users: "{{ list_of_users + [ user.key ] }}"
      when:
        - system_users_elementcheck_individual
        - inventory_hostname in system_users_create_on_hosts[user.key]
  when: user.key not in list_of_users
  # user already found in group assignments, no second acknowledge necessary

- name: MMN users - Print result
  ansible.builtin.debug:
    msg: "Host {{ inventory_hostname }} will get the following users {{ list_of_users }}"
