---
- name: "MMN cacert - Assemble CA vars"
  ansible.builtin.set_fact:
    cacert_filename_cacert: "{{ cacert_ca.key }}_ca_{{ cacert_tag_certificate }}.pem"
    cacert_filename_cakey: "{{ cacert_ca.key }}_ca_{{ cacert_tag_privatekey }}.pem"
- name: "MMN cacert - CA cert destination path"
  ansible.builtin.set_fact:
    cacert_path_cacert_targethost: "{{ cacert_openssl_path_certificates }}/{{ cacert_filename_cacert }}"
    cacert_path_cakey_targethost: "{{ cacert_openssl_path_keys }}/{{ cacert_ca.key }}_ca_{{ cacert_tag_privatekey }}.pem"
