---
- name: "MMN cacert - Assemble CA vars"
  ansible.builtin.set_fact:
    cacert_filename_cacert: "{{ cacert_ca.key }}_ca_{{ cacert_tag_certificate }}.pem"
    cacert_filename_cakey: "{{ cacert_ca.key }}_ca_{{ cacert_tag_privatekey }}.pem"
- name: "MMN cacert - CA cert destination path"
  ansible.builtin.set_fact:
    cacert_path_cacert: "{{ cacert_openssl_path_certificate_ca }}/{{ cacert_filename_cacert }}"
    cacert_path_cakey: "{{ cacert_openssl_path_key_ca }}/{{ cacert_ca.key }}_ca_{{ cacert_tag_privatekey }}.pem"
