---
- name: Setting OS variables
  ansible.builtin.include_vars: "{{lookup('ansible.builtin.first_found', params)}}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "default.yml"
      paths:
        - "vars"
- name: Run install tasks
  ansible.builtin.import_tasks: install.yml
- name: create databases
  community.mysql.mysql_db:
    check_implicit_admin: true
    name: "{{ mariadb_databases }}"
    state: present
      #login_user: "root"
      #login_password: "{{ mariadb_rootpw }}"
    login_unix_socket: "/var/run/mysqld/mysqld.sock"
    config_file: "/etc/mysql/my.cnf"
  when: mariadb_databases is defined
- name: "MMN mariadb - Manage users"
  community.mysql.mysql_user:
    name: "{{ mariadbuser.name }}"
    password: "{{ mariadbuser.password }}"
    priv: "{{ mariadbuser.priv }}"
    state: "{{ mariadbuser.state }}"
    login_unix_socket: "{{ mariadbuser.login_unix_socket }}"
    host: "{{ mariadbuser.host }}"
  loop: "{{ mariadb_users }}"
  loop_control:
    loop_var: mariadbuser
  when: mariadb_users is defined
