---
- name : 복원 작업
  hosts: webservers
  tasks: 
  ###############################################
  #  1) 방화벽 제거 - http(80/tcp)
  #  2) 웹 서비스 종료 - httpd, firewalld 
  #  3) 설정 파일 삭제 - index.html
  #  4) 웹 패키지 삭제 - httpd
  #  ############################################

  - name : (1) 방화벽 제거
    ansible.posix.firewalld:
      service: http
      permanent: true
      state: disabled
      immediate: true
    
  - name : 서비스 종료 - httpd 
    ansible.builtin.service:
      name: httpd
      state: stopped
      enabled: false

  - name : 서비스 종료 - firewalld
    ansible.builtin.service:
      name: firewalld
      state: stopped
      enabled: false

  - name: 설정 파일 삭제 - /var/www/html/index.html
    ansible.builtin.file:
      path: /var/www/html/index.html
      state: absent
    
  - name : 패키지 삭제 - httpd.service
    ansible.builtin.yum:
      name: httpd
      state: absent








