---
- name: 웹 서버 설정
  hosts: webservers
  tasks: 
   ###############################################
   #  1) 패키지 설치 - httpd
   #  2) 서비스 설정 - /var/www/html/index.html
   #  3) 웹 서버 기동 - httpd.service
   #  4) 방화벽 등록  - http(80/tcp)
   #  5) SELinux
   #  ############################################
   
  - name : 패키지 설치
    # yum install httpd firewalld
    ansible.builtin.yum:
      name: 
        - httpd
        - firewalld
      state: present

  # cp files/index.html /var/www/html/index.html
  - name : 서비스 설정
    ansible.builtin.copy:
      src: files/index.html
      dest: /var/www/html/index.html
      owner: root
      grop: root
      mode: '0644'

  # systemcl enable --now httpd
  - name : 서비스 기동
    ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

  - name : 서비스 기동
    ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

  - name : 방화벽 등록
  # firewall-cmd --permanent --add-service=https
  # firewall-cmd --reload
    ansible.posix.firewalld:
      service: http
      immediate: true   
      permanent: true
      state: enabled