---
kind: Pod
apiVersion: v1
metadata:
  name: web-pvc
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - name: web-port
        containerPort: 80
      # 2) 볼륨 마운트
      # mount [PVC]  /usr/share/nginx/html
      volumeMounts:
        - name:  html
          mountPath: /usr/share/nginx/html
    # 1) 볼륨 정의
  volumes:
    - name:  html
      persistentVolumeClaim:
        claimName: myclaim
      