---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim
spec:
  # 볼륨 특성으로 선택
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  volumeMode: Filesystem
  storageClassName: manual  
