
    #- name: "MMN cacert - Make sure CA cert is there"
    #  community.crypto.x509_certificate:
    #    acme_accountkey_path: "{{ cacert_ca.value.acme_accountkey_path | default(omit) }}"
    #    acme_chain: "{{ cacert_ca.value.acme_chain | default(omit) }}"
    #    acme_challenge_path: "{{ cacert_ca.value.acme_challenge_path | default(omit) }}"
    #    acme_directory: "{{ cacert_ca.value.acme_directory | default(omit) }}"
    #    attributes: "{{ cacert_ca.value.attributes | default(omit) }}"
    #    backup: "{{ cacert_ca.value.backup | default(omit) }}"
    #    csr_content: "{{ cacert_ca.value.csr_content | default(omit) }}"
    #    csr_path: "{{ cacert_ca.value.csr_path | default(omit) }}"
    #    entrust_api_client_cert_key_path: "{{ cacert_ca.value.entrust_api_client_cert_key_path | default(omit) }}"
    #    entrust_api_client_cert_path: "{{ cacert_ca.value.entrust_api_client_cert_path | default(omit) }}"
    #    entrust_api_key: "{{ cacert_ca.value.entrust_api_key | default(omit) }}"
    #    entrust_api_specification_path: "{{ cacert_ca.value.entrust_api_specification_path | default(omit) }}"
    #    entrust_api_user: "{{ cacert_ca.value.entrust_api_user | default(omit) }}"
    #    entrust_cert_type: "{{ cacert_ca.value.entrust_cert_type | default(omit) }}"
    #    entrust_not_after: "{{ cacert_ca.value.entrust_not_after | default(omit) }}"
    #    entrust_requester_email: "{{ cacert_ca.value.entrust_requester_email | default(omit) }}"
    #    entrust_requester_name: "{{ cacert_ca.value.entrust_requester_name | default(omit) }}"
    #    entrust_requester_phone: "{{ cacert_ca.value.entrust_requester_phone | default(omit) }}"
    #    force: "{{ cacert_ca.value.force | default(omit) }}"
    #    group: "{{ cacert_ca.value.group | default(omit) }}"
    #    ignore_timestamps: "{{ cacert_ca.value.ignore_timestamps | default(omit) }}"
    #    mode: "{{ cacert_ca.value.mode | default(omit) }}"
    #    ownca_content: "{{ cacert_ca.value.ownca_content | default(omit) }}"
    #    ownca_create_authority_key_identifier: "{{ cacert_ca.value.ownca_create_authority_key_identifier | default(omit) }}"
    #    ownca_create_subject_key_identifier: "{{ cacert_ca.value.ownca_create_subject_key_identifier | default(omit) }}"
    #    ownca_digest: "{{ cacert_ca.value.ownca_digest | default(omit) }}"
    #    ownca_not_after: "{{ cacert_ca.value.ownca_not_after | default(omit) }}"
    #    ownca_not_before: "{{ cacert_ca.value.ownca_not_before | default(omit) }}"
    #    ownca_path: "{{ cacert_ca.value.ownca_path | default(omit) }}"
    #    ownca_privatekey_content: "{{ cacert_ca.value.ownca_privatekey_content | default(omit) }}"
    #    ownca_privatekey_passphrase: "{{ cacert_ca.value.ownca_privatekey_passphrase | default(omit) }}"
    #    ownca_privatekey_path: "{{ cacert_ca.value.ownca_privatekey_path | default(omit) }}"
    #    ownca_version: "{{ cacert_ca.value.ownca_version | default(omit) }}"
    #    owner: "{{ cacert_ca.value.owner | default(omit) }}"
    #    path: "{{ cacert_ca.value.path | default(omit) }}"
    #    privatekey_content: "{{ cacert_ca.value.privatekey_content | default(omit) }}"
    #    privatekey_passphrase: "{{ cacert_ca.value.privatekey_passphrase | default(omit) }}"
    #    privatekey_path: "{{ cacert_ca.value.privatekey_path | default(omit) }}"
    #    provider: "{{ cacert_ca.value.provider | default(omit) }}"
    #    return_content: "{{ cacert_ca.value.return_content | default(omit) }}"
    #    select_crypto_backend: "{{ cacert_ca.value.select_crypto_backend | default(omit) }}"
    #    selevel: "{{ cacert_ca.value.selevel | default(omit) }}"
    #    selfsigned_create_subject_key_identifier: "{{ cacert_ca.value.selfsigned_create_subject_key_identifier | default(omit) }}"
    #    selfsigned_digest: "{{ cacert_ca.value.selfsigned_digest | default(omit) }}"
    #    selfsigned_not_after: "{{ cacert_ca.value.selfsigned_not_after | default(omit) }}"
    #    selfsigned_not_before: "{{ cacert_ca.value.selfsigned_not_before | default(omit) }}"
    #    selfsigned_version: "{{ cacert_ca.value.selfsigned_version | default(omit) }}"
    #    serole: "{{ cacert_ca.value.serole | default(omit) }}"
