---
- name: "MMN cacert - Build CA path variables"
  ansible.builtin.include_tasks: paths_ca.yml

- name: "MMN cacert - Build Server path variables"
  ansible.builtin.include_tasks: paths_server.yml

- name: "MMN cacert - Check if CA cert exists"
  ansible.builtin.stat:
    path: "{{ cacert_path_cacert }}"
  register: stat_certificate_ca

- name: "MMN cacert - Load existing ca cert"
  become: True
  slurp:
    src: "{{ cacert_path_cacert }}"
  register: existing_cacert_ca_cert2
  when: stat_certificate_ca.stat.exists

- name: "MMN cacert | Set CA cert as fact"
  ansible.builtin.set_fact:
    cacert_ca_cert2:
      certificate: "{{ existing_cacert_ca_cert2.content | b64decode }}"
  when: stat_certificate_ca.stat.exists








- name: "MMN cacert - Update trust store"
  become: True
  ansible.builtin.command: update-ca-certificates
  changed_when: True


