---
kind: Pod
apiVersion: v1
metadata:
  name: mongo-db
spec:
  containers:
    - name: mongo
      image: mongo:8.0.15
      ports:
        - containerPort: 27017
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: example
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: machinerunning
          topologyKey: kubernetes.io/hostname