# PSQL
- name: "MMN Podman - Safety wait for psql first start"
  ansible.builtin.pause:
    seconds: "{{ podman_container_plugin_psql_waittime | default('10') }}"
  when:
    - podman_container_plugin_psql is defined
    - podman_containers | map(attribute='name') | select('in', podman_container_plugin_psql) | list | length > 0
- name: "MMN Podman - Prepare calling psqlserver role"
  ansible.builtin.set_fact:
    psqlserver_containermode: true
  when:
    - podman_container_plugin_psql is defined
    - podman_containers | map(attribute='name') | select('in', podman_container_plugin_psql) | list | length > 0
- name: "MMN Podman - Calling psqlserver role"
  ansible.builtin.include_role:
    name: imp1sh.ansible_managemynetwork.ansible_psqlserver 
    tasks_from: container_2.yml
  loop: "{{ psqlserver_instances | dict2items }}"
  loop_control:
    loop_var: "psqlserver_instance"
  when:
    - podman_container_plugin_psql is defined
    - podman_containers | map(attribute='name') | select('in', podman_container_plugin_psql) | list | length > 0
    - not psqlserver_isreplica | default(False)
