---
# tasks file for ansible_podman
- name: "MMN Podman - Prepare and install packagessystemd tasks"
  ansible.builtin.include_tasks:
    file: 0install.yml

- name: "MMN Podman - Network and more"
  ansible.builtin.include_tasks:
    file: 1prepare.yml

      # FIXME Currently broken, see https://github.com/containers/ansible-podman-collections/issues/924#issuecomment-2807192548
      #- name: MMN Podman - Manage secrets
      #  containers.podman.podman_secret:
      #    name: "{{ item.name }}"
      #    state: "{{ item.state }}"
      #    data: "{{ item.data }}"
      #    path: "{{ item.path | default(omit) }}"
      #    debug: "{{ item.debug | default(omit) }}"
      #    driver: "{{ item.driver | default('file') }}"
      #    driver_opts: "{{ item.driver_opts | default(omit) }}"
      #    env: "{{ item.env | default(omit) }}"
      #    executable: "{{ item.executable | default(omit) }}"
      #    force: "{{ item.force | default(omit) }}"
      #    labels: "{{ item.labels | default(omit) }}"
      #    skip_existing: "{{ item.skip_existing | default(omit) }}"
      #  loop: "{{ podman_secrets }}"

- name: "MMN Podman - Deploy application configuration for supported plugin 1st run"
  ansible.builtin.include_tasks:
    file: 2plugins.yml
  when: ( podman_container_plugin_psql is defined ) or ( podman_container_plugin_borgmatic is defined ) or ( podman_container_plugin_pdnsauth is defined )
  # add or condition for additional plugins, I need to list them all here

- name: "MMN Podman - Create containers"
  containers.podman.podman_containers:
    containers: "{{ podman_containers }}"
  when:
    - podman_containers is defined

- name: "MMN Podman - Deploy application configuration for supported plugin 2nd run"
  ansible.builtin.include_tasks:
    file: 2plugins2.yml
  when: podman_container_plugin_psql is defined
  # add or condition for additional plugins, I need to list them all here

- name: "MMN Podman - Post tasks"
  ansible.builtin.include_tasks:
    file: 4post.yml
  when: podman_containers is defined

# BORGMATIC
- name: "MMN Podman - Calling borgmatic role"
  ansible.builtin.include_role:
    name: imp1sh.ansible_managemynetwork.ansible_borgmatic
    tasks_from: "init_container.yml"
  when:
    - podman_container_plugin_borgmatic is defined
    - podman_containers | map(attribute='name') | intersect(podman_container_plugin_borgmatic) | length > 0
