---
- name: "MMN Podman - prepare calling pdnsauth role"
  ansible.builtin.set_fact:
    pdns_containermode: true
- name: "MMN Podman - Calling pdnsauth role"
  ansible.builtin.include_role:
    name: imp1sh.ansible_managemynetwork.ansible_pdnsauth
- name: "MMN Podman - Calling cacert role"
  ansible.builtin.include_role:
    name: imp1sh.ansible_managemynetwork.ansible_cacert
