---
- name: "MMN Podman - prepare calling psqlserver role"
  ansible.builtin.set_fact:
    psqlserver_containermode: true
- name: "MMN Podman - Calling psqlserver role"
  ansible.builtin.include_role:
    name: imp1sh.ansible_managemynetwork.ansible_psqlserver 
      # cacert role not ready for use
      #- name: "MMN Podman - Calling cacert role"
      #  ansible.builtin.include_role:
      #    name: imp1sh.ansible_managemynetwork.ansible_cacert
